//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.SALIDA_EMPLEADO = new HashSet<SALIDA_EMPLEADO>();
            this.VACACIONES = new HashSet<VACACIONES>();
            this.PERMISO = new HashSet<PERMISO>();
            this.LICENCIA = new HashSet<LICENCIA>();
            this.NOMINA = new HashSet<NOMINA>();
        }
    
        public int ID_EMPLEADO { get; set; }
        public string CODIGO_EMPLEADO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string TELÉFONO { get; set; }
        public Nullable<int> ID_DEPARTAMENTO { get; set; }
        public Nullable<int> ID_CARGO { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public Nullable<decimal> SALARIO { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALIDA_EMPLEADO> SALIDA_EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VACACIONES> VACACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISO> PERMISO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICENCIA> LICENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOMINA> NOMINA { get; set; }
    }
}
