//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINA
    {
        public int ID_NOMINA { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<decimal> MONTO_TOTAL { get; set; }
        public Nullable<int> ID_EMPLEADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
