//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALIDA_EMPLEADO
    {
        public int ID_SALIDA_EMPLEADO { get; set; }
        public Nullable<int> ID_EMPLEADO { get; set; }
        public string TIPO_SALIDA { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
