//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACACIONES
    {
        public int ID_VACACIONES { get; set; }
        public Nullable<int> ID_EMPLEADO { get; set; }
        public Nullable<System.DateTime> DESDE { get; set; }
        public Nullable<System.DateTime> HASTA { get; set; }
        public string CORRESPONDIENTE { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
